In [1]:
import numpy as np
import pandas as pd

In [33]:
dataset_df = pd.read_csv('../../case data/hose-price-prediction/train.csv',index_col='Id',na_filter=True)
dataset = np.genfromtxt('../../case data/hose-price-prediction/train.csv',delimiter=',',skip_header=True)
dataset

array([[1.00000e+00, 6.00000e+01,         nan, ...,         nan,
                nan, 2.08500e+05],
       [2.00000e+00, 2.00000e+01,         nan, ...,         nan,
                nan, 1.81500e+05],
       [3.00000e+00, 6.00000e+01,         nan, ...,         nan,
                nan, 2.23500e+05],
       ...,
       [1.45800e+03, 7.00000e+01,         nan, ...,         nan,
                nan, 2.66500e+05],
       [1.45900e+03, 2.00000e+01,         nan, ...,         nan,
                nan, 1.42125e+05],
       [1.46000e+03, 2.00000e+01,         nan, ...,         nan,
                nan, 1.47500e+05]])

In [41]:
def bin_split(data, feature, value):
    mat0 = data[np.nonzero(data[:, feature] > value)[0],:][0]
    mat1 = data[np.nonzero(data[:, feature] <= value)[0],:][0]
    return mat0, mat1

In [67]:
def bin_split_df(data, feature, value):
    mat0 = data.iloc[np.nonzero(data[feature].values > value)[0],:].iloc[0]
    mat1 = data.iloc[np.nonzero(data[feature].values <= value)[0], :].iloc[0]
    return mat0, mat1

In [63]:
mat0,mat1 = bin_split(dataset,1,20)
mat0.shape,mat1.shape

((81,), (81,))

In [68]:
m0,m1 = bin_split_df(dataset_df,'MSSubClass',20)

In [71]:
m0.values

array([60, 'RL', 65.0, 8450, 'Pave', nan, 'Reg', 'Lvl', 'AllPub',
       'Inside', 'Gtl', 'CollgCr', 'Norm', 'Norm', '1Fam', '2Story', 7, 5,
       2003, 2003, 'Gable', 'CompShg', 'VinylSd', 'VinylSd', 'BrkFace',
       196.0, 'Gd', 'TA', 'PConc', 'Gd', 'TA', 'No', 'GLQ', 706, 'Unf', 0,
       150, 856, 'GasA', 'Ex', 'Y', 'SBrkr', 856, 854, 0, 1710, 1, 0, 2,
       1, 3, 1, 'Gd', 8, 'Typ', 0, nan, 'Attchd', 2003.0, 'RFn', 2, 548,
       'TA', 'TA', 'Y', 0, 61, 0, 0, 0, 0, nan, nan, nan, 0, 2, 2008,
       'WD', 'Normal', 208500], dtype=object)

In [72]:
m1.values


array([20, 'RL', 80.0, 9600, 'Pave', nan, 'Reg', 'Lvl', 'AllPub', 'FR2',
       'Gtl', 'Veenker', 'Feedr', 'Norm', '1Fam', '1Story', 6, 8, 1976,
       1976, 'Gable', 'CompShg', 'MetalSd', 'MetalSd', 'None', 0.0, 'TA',
       'TA', 'CBlock', 'Gd', 'TA', 'Gd', 'ALQ', 978, 'Unf', 0, 284, 1262,
       'GasA', 'Ex', 'Y', 'SBrkr', 1262, 0, 0, 1262, 0, 1, 2, 0, 3, 1,
       'TA', 6, 'Typ', 1, 'TA', 'Attchd', 1976.0, 'RFn', 2, 460, 'TA',
       'TA', 'Y', 298, 0, 0, 0, 0, 0, nan, nan, nan, 0, 5, 2007, 'WD',
       'Normal', 181500], dtype=object)